server.port: 8081

spring:
  application:
  name: pagamento

  #JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  #Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/desafio
    username: postgres
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher